name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build STM32CubeIde project
      uses: xanderhendriks/action-build-stm32cubeide@v10.0
            
